ruian_db:
  schema_search_path: public, postgis
  adapter: postgresql
  encoding: utf8
  database: ruian
  pool: 10
  username: ob
  password: ob
  host: localhost

test:
  schema_search_path: public, postgis
  adapter: postgresql
  encoding: utf8
  database: somedb_ruian
  pool: 10
  username: ob


